# Generated by Django 5.1.3 on 2024-11-26 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='documents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('user_id', models.IntegerField()),
                ('roll_no', models.IntegerField(null=True)),
                ('file', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='PeerEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluator_id', models.IntegerField()),
                ('evaluation_date', models.DateTimeField()),
                ('evaluation', models.TextField()),
                ('feedback', models.TextField()),
                ('score', models.IntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.documents')),
            ],
        ),
        migrations.AddField(
            model_name='documents',
            name='peer_evaluations',
            field=models.ManyToManyField(to='app.peerevaluation'),
        ),
    ]
