# Generated by Django 5.1.3 on 2024-11-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_email_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='uid',
            field=models.IntegerField(unique=True),
        ),
    ]
