# Generated by Django 5.1.3 on 2024-11-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_peerevaluation_evaluation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='peerevaluation',
            name='count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
