# Generated by Django 5.1.3 on 2024-12-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_peerevaluation_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='peerevaluation',
            name='max_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
