# Generated by Django 5.1.3 on 2024-12-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_peerevaluation_max_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peerevaluation',
            name='count',
        ),
        migrations.RemoveField(
            model_name='peerevaluation',
            name='max_count',
        ),
        migrations.AddField(
            model_name='peerevaluation',
            name='evaluated',
            field=models.BooleanField(default=False),
        ),
    ]
