# Generated by Django 5.1.3 on 2024-12-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_coursetopics_llmevaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmevaluation',
            name='answer',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
