# Generated by Django 5.1.3 on 2024-12-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_llmevaluation_ai'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmevaluation',
            name='aggregate',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
