# Generated by Django 5.1.3 on 2024-12-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_llmevaluation_aggregate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmevaluation',
            name='ai',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='llmevaluation',
            name='score',
            field=models.TextField(),
        ),
    ]
