# Generated by Django 5.1.3 on 2024-12-05 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_llmevaluation_ai_alter_llmevaluation_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llmevaluation',
            name='CourseTopic',
        ),
        migrations.RemoveField(
            model_name='llmevaluation',
            name='student',
        ),
        migrations.DeleteModel(
            name='CourseTopics',
        ),
        migrations.DeleteModel(
            name='LLMEvaluation',
        ),
    ]
